leftnav:
- identifier: 9b0b66f5-9cf8-fd9b-1367-f4ebff59fac5
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: e5547d7d-e7a0-a5c7-9c95-7d9da9851ca6
  name: Course Textbook
  pageRef: /pages/course-textbook
  weight: 20
- identifier: 0a02dfd8-fe36-99e5-18e6-ce347b8587b3
  name: Exams
  pageRef: /pages/exams
  weight: 30
